[package]
name = "monarch_cpp_static_libs"
version = "0.0.1"
authors = ["Facebook"]
edition = "2021"
license = "MIT"
description = "Builds static rdma-core libraries from source"
links = "monarch_cpp_static_libs"
build = "build.rs"

[build-dependencies]
build_utils = { path = "../build_utils" }
